--------------------------------------------------------
-- Archivo creado  - sábado-diciembre-02-2017   
--------------------------------------------------------
DROP TABLE "PROYECTO"."ALIMENTOS" cascade constraints;
DROP TABLE "PROYECTO"."CONSUMOS" cascade constraints;
DROP TABLE "PROYECTO"."DOSIS" cascade constraints;
DROP TABLE "PROYECTO"."ENFERMEDADES" cascade constraints;
DROP TABLE "PROYECTO"."GUACHERAS" cascade constraints;
DROP TABLE "PROYECTO"."MADRES" cascade constraints;
DROP TABLE "PROYECTO"."MEDICAMENTOS" cascade constraints;
DROP TABLE "PROYECTO"."PADRES" cascade constraints;
DROP TABLE "PROYECTO"."PESOS" cascade constraints;
DROP TABLE "PROYECTO"."TERNERAS" cascade constraints;
DROP TABLE "PROYECTO"."TIENE_ENFERMEDADES" cascade constraints;
DROP TABLE "PROYECTO"."UNIDADES" cascade constraints;
DROP TABLE "PROYECTO"."USUARIOS" cascade constraints;
DROP SEQUENCE "PROYECTO"."SEQ_ID_ALIMENTO";
DROP SEQUENCE "PROYECTO"."SEQ_ID_CONSUMO";
DROP SEQUENCE "PROYECTO"."SEQ_ID_DOSIS";
DROP SEQUENCE "PROYECTO"."SEQ_ID_ENFERMEDAD";
DROP SEQUENCE "PROYECTO"."SEQ_ID_MADRE";
DROP SEQUENCE "PROYECTO"."SEQ_ID_MEDICAMENTO";
DROP SEQUENCE "PROYECTO"."SEQ_ID_PADRE";
DROP SEQUENCE "PROYECTO"."SEQ_ID_PESO";
DROP SEQUENCE "PROYECTO"."SEQ_ID_TERNERA";
DROP SEQUENCE "PROYECTO"."SEQ_ID_TIENE_ENF";
DROP SEQUENCE "PROYECTO"."SEQ_ID_USUARIO";
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ALIMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_ALIMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 91 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_CONSUMO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_CONSUMO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DOSIS
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_DOSIS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ENFERMEDAD
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_ENFERMEDAD"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_MADRE
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_MADRE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_MEDICAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_MEDICAMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PADRE
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_PADRE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PESO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_PESO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_TERNERA
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_TERNERA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_TIENE_ENF
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_TIENE_ENF"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_USUARIO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ALIMENTOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."ALIMENTOS" 
   (	"ID_ALIMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(25 BYTE), 
	"COSTO_UNIDAD" NUMBER(7,2), 
	"CANTIDAD" NUMBER(7,2), 
	"ID_UNIDAD" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSUMOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."CONSUMOS" 
   (	"FECHA" DATE, 
	"CANTIDAD" NUMBER(7,2), 
	"ID_ALIMENTO" NUMBER(*,0), 
	"ID_TERNERA" NUMBER(*,0), 
	"ID_CONSUMO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOSIS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."DOSIS" 
   (	"FECHA" DATE, 
	"CANTIDAD" NUMBER(4,2), 
	"ID_MEDICAMENTO" NUMBER(*,0), 
	"ID_TERNERA" NUMBER(*,0), 
	"ID_DOSIS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENFERMEDADES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."ENFERMEDADES" 
   (	"ID_ENFERMEDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"GRADO_GRAVEDAD" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUACHERAS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."GUACHERAS" 
   (	"ID_GUACHERA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"ID_USUARIO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MADRES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."MADRES" 
   (	"ID_MADRE" NUMBER(*,0), 
	"NRO_CARAVANA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."MEDICAMENTOS" 
   (	"ID_MEDICAMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DOSIS" VARCHAR2(50 BYTE), 
	"COSTO" NUMBER(7,2), 
	"FEC_DESDE" DATE, 
	"FEC_HASTA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PADRES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."PADRES" 
   (	"ID_PADRE" NUMBER(*,0), 
	"NRO_CARAVANA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PESOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."PESOS" 
   (	"ID_PESO" NUMBER(*,0), 
	"TIPO_REGISTRO" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"PESO" NUMBER(6,2), 
	"ID_TERNERA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TERNERAS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."TERNERAS" 
   (	"ID_TERNERA" NUMBER(*,0), 
	"NRO_CARAVANA" NUMBER(*,0), 
	"ID_GUACHERA" NUMBER(*,0), 
	"ID_PADRE" NUMBER(*,0), 
	"ID_MADRE" NUMBER(*,0), 
	"FEC_NACIMIENTO" DATE, 
	"PESO_NACIMIENTO" NUMBER(6,2), 
	"RAZA" VARCHAR2(10 BYTE), 
	"PARTO" VARCHAR2(10 BYTE), 
	"FEC_MUERTE" DATE, 
	"CAUSA_MUERTE" VARCHAR2(500 BYTE), 
	"FEC_BAJA" DATE, 
	"MOTIVO_BAJA" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIENE_ENFERMEDADES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."TIENE_ENFERMEDADES" 
   (	"FEC_DESDE" DATE, 
	"FEC_HASTA" DATE, 
	"OBSERVACION" VARCHAR2(250 BYTE), 
	"ID_ENFERMEDAD" NUMBER(*,0), 
	"ID_TERNERA" NUMBER(*,0), 
	"ID_TIENE_ENF" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNIDADES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."UNIDADES" 
   (	"ID_UNIDAD" NUMBER(*,0), 
	"UNIDAD" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"PERFIL" VARCHAR2(10 BYTE), 
	"CONTRASEÑA" VARCHAR2(16 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PROYECTO.ALIMENTOS
SET DEFINE OFF;
Insert into PROYECTO.ALIMENTOS (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values ('20','Leche','0','-5','2');
Insert into PROYECTO.ALIMENTOS (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values ('30','Sustituto Lacteo','0','0','1');
Insert into PROYECTO.ALIMENTOS (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values ('40','Iniciador','0','-3','1');
Insert into PROYECTO.ALIMENTOS (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values ('50','Racion','0','0','1');
Insert into PROYECTO.ALIMENTOS (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values ('10','Calostro Natural','0','0','2');
Insert into PROYECTO.ALIMENTOS (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values ('11','Calostro Forzado','0','0','2');
REM INSERTING into PROYECTO.CONSUMOS
SET DEFINE OFF;
Insert into PROYECTO.CONSUMOS (FECHA,CANTIDAD,ID_ALIMENTO,ID_TERNERA,ID_CONSUMO) values (to_date('09/10/17','DD/MM/RR'),'5','20','1','1');
Insert into PROYECTO.CONSUMOS (FECHA,CANTIDAD,ID_ALIMENTO,ID_TERNERA,ID_CONSUMO) values (to_date('01/11/17','DD/MM/RR'),'3','40','4','2');
REM INSERTING into PROYECTO.DOSIS
SET DEFINE OFF;
REM INSERTING into PROYECTO.ENFERMEDADES
SET DEFINE OFF;
Insert into PROYECTO.ENFERMEDADES (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values ('2','DIARREA','2');
Insert into PROYECTO.ENFERMEDADES (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values ('3','DIARREA','3');
Insert into PROYECTO.ENFERMEDADES (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values ('5','NEUMONIA','2');
Insert into PROYECTO.ENFERMEDADES (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values ('6','NEUMONIA','3');
Insert into PROYECTO.ENFERMEDADES (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values ('1','DIARREA','1');
Insert into PROYECTO.ENFERMEDADES (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values ('4','NEUMONIA','1');
REM INSERTING into PROYECTO.GUACHERAS
SET DEFINE OFF;
Insert into PROYECTO.GUACHERAS (ID_GUACHERA,NOMBRE,ID_USUARIO) values ('1','GU01','51');
Insert into PROYECTO.GUACHERAS (ID_GUACHERA,NOMBRE,ID_USUARIO) values ('2','GU02','53');
Insert into PROYECTO.GUACHERAS (ID_GUACHERA,NOMBRE,ID_USUARIO) values ('3','GU03','54');
REM INSERTING into PROYECTO.MADRES
SET DEFINE OFF;
Insert into PROYECTO.MADRES (ID_MADRE,NRO_CARAVANA) values ('1','565656565');
Insert into PROYECTO.MADRES (ID_MADRE,NRO_CARAVANA) values ('2','6565656565');
REM INSERTING into PROYECTO.MEDICAMENTOS
SET DEFINE OFF;
REM INSERTING into PROYECTO.PADRES
SET DEFINE OFF;
Insert into PROYECTO.PADRES (ID_PADRE,NRO_CARAVANA) values ('1','555555555');
Insert into PROYECTO.PADRES (ID_PADRE,NRO_CARAVANA) values ('2','666666666');
REM INSERTING into PROYECTO.PESOS
SET DEFINE OFF;
Insert into PROYECTO.PESOS (ID_PESO,TIPO_REGISTRO,FECHA,PESO,ID_TERNERA) values ('1','SEMANAL',to_date('21/10/16','DD/MM/RR'),'16','1');
REM INSERTING into PROYECTO.TERNERAS
SET DEFINE OFF;
Insert into PROYECTO.TERNERAS (ID_TERNERA,NRO_CARAVANA,ID_GUACHERA,ID_PADRE,ID_MADRE,FEC_NACIMIENTO,PESO_NACIMIENTO,RAZA,PARTO,FEC_MUERTE,CAUSA_MUERTE,FEC_BAJA,MOTIVO_BAJA) values ('21','545454','1','1','2',to_date('25/11/15','DD/MM/RR'),'11','HOLANDO','NORMAL',to_date('01/01/00','DD/MM/RR'),null,to_date('01/01/00','DD/MM/RR'),null);
Insert into PROYECTO.TERNERAS (ID_TERNERA,NRO_CARAVANA,ID_GUACHERA,ID_PADRE,ID_MADRE,FEC_NACIMIENTO,PESO_NACIMIENTO,RAZA,PARTO,FEC_MUERTE,CAUSA_MUERTE,FEC_BAJA,MOTIVO_BAJA) values ('22','6456565','1','2','1',to_date('22/11/16','DD/MM/RR'),'13','HOLANDO','NORMAL',to_date('01/01/00','DD/MM/RR'),null,to_date('01/01/00','DD/MM/RR'),null);
Insert into PROYECTO.TERNERAS (ID_TERNERA,NRO_CARAVANA,ID_GUACHERA,ID_PADRE,ID_MADRE,FEC_NACIMIENTO,PESO_NACIMIENTO,RAZA,PARTO,FEC_MUERTE,CAUSA_MUERTE,FEC_BAJA,MOTIVO_BAJA) values ('23','544445','2','2','2',to_date('15/05/15','DD/MM/RR'),'11,5','HOLANDO','NORMAL',to_date('01/01/00','DD/MM/RR'),null,to_date('01/01/00','DD/MM/RR'),null);
Insert into PROYECTO.TERNERAS (ID_TERNERA,NRO_CARAVANA,ID_GUACHERA,ID_PADRE,ID_MADRE,FEC_NACIMIENTO,PESO_NACIMIENTO,RAZA,PARTO,FEC_MUERTE,CAUSA_MUERTE,FEC_BAJA,MOTIVO_BAJA) values ('1','66555','1','1','2',to_date('12/10/16','DD/MM/RR'),'15','HOLANDO','NORMAL',to_date('01/01/00','DD/MM/RR'),null,to_date('01/01/00','DD/MM/RR'),null);
Insert into PROYECTO.TERNERAS (ID_TERNERA,NRO_CARAVANA,ID_GUACHERA,ID_PADRE,ID_MADRE,FEC_NACIMIENTO,PESO_NACIMIENTO,RAZA,PARTO,FEC_MUERTE,CAUSA_MUERTE,FEC_BAJA,MOTIVO_BAJA) values ('4','6646','2','2','2',to_date('12/04/17','DD/MM/RR'),'12','HOLANDO','NORMAL',to_date('01/01/00','DD/MM/RR'),null,to_date('01/01/00','DD/MM/RR'),null);
REM INSERTING into PROYECTO.TIENE_ENFERMEDADES
SET DEFINE OFF;
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('28/11/15','DD/MM/RR'),to_date('30/11/15','DD/MM/RR'),null,'1','21','21');
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('01/04/16','DD/MM/RR'),to_date('05/04/16','DD/MM/RR'),null,'5','21','22');
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('25/11/16','DD/MM/RR'),to_date('30/11/16','DD/MM/RR'),null,'3','22','23');
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('05/01/17','DD/MM/RR'),to_date('20/01/17','DD/MM/RR'),null,'3','22','24');
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('25/05/15','DD/MM/RR'),to_date('05/06/15','DD/MM/RR'),null,'2','23','25');
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('26/07/16','DD/MM/RR'),to_date('15/08/16','DD/MM/RR'),null,'5','23','26');
Insert into PROYECTO.TIENE_ENFERMEDADES (FEC_DESDE,FEC_HASTA,OBSERVACION,ID_ENFERMEDAD,ID_TERNERA,ID_TIENE_ENF) values (to_date('10/10/17','DD/MM/RR'),to_date('15/10/17','DD/MM/RR'),'GRAVE','1','1','1');
REM INSERTING into PROYECTO.UNIDADES
SET DEFINE OFF;
Insert into PROYECTO.UNIDADES (ID_UNIDAD,UNIDAD) values ('1','KG');
Insert into PROYECTO.UNIDADES (ID_UNIDAD,UNIDAD) values ('2','L');
REM INSERTING into PROYECTO.USUARIOS
SET DEFINE OFF;
Insert into PROYECTO.USUARIOS (ID_USUARIO,USUARIO,NOMBRE,APELLIDO,PERFIL,CONTRASEÑA) values ('53','jose.rodriguez','Jose','Rodriguez','ENCARGADO','21235454654654');
Insert into PROYECTO.USUARIOS (ID_USUARIO,USUARIO,NOMBRE,APELLIDO,PERFIL,CONTRASEÑA) values ('51','pedro.dias','Pedro ','Dias','ENCARGADO','22558866');
Insert into PROYECTO.USUARIOS (ID_USUARIO,USUARIO,NOMBRE,APELLIDO,PERFIL,CONTRASEÑA) values ('54','juan.garcia','Juan','Garcia','ENCARGADO','21325465465465');
--------------------------------------------------------
--  DDL for Index UK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_USUARIO" ON "PROYECTO"."USUARIOS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIENE_ENFERMEDAD1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_TIENE_ENFERMEDAD1" ON "PROYECTO"."TIENE_ENFERMEDADES" ("ID_TIENE_ENF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_USUARIO" ON "PROYECTO"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DOSIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_DOSIS" ON "PROYECTO"."DOSIS" ("ID_MEDICAMENTO", "ID_TERNERA", "FECHA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_TERNERA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_TERNERA" ON "PROYECTO"."TERNERAS" ("NRO_CARAVANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DOSIS1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_DOSIS1" ON "PROYECTO"."DOSIS" ("ID_DOSIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEDICAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_MEDICAMENTO" ON "PROYECTO"."MEDICAMENTOS" ("ID_MEDICAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GUACHERA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_GUACHERA" ON "PROYECTO"."GUACHERAS" ("ID_GUACHERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PADRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_PADRE" ON "PROYECTO"."PADRES" ("ID_PADRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_UNIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_UNIDAD" ON "PROYECTO"."UNIDADES" ("UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ALIMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_ALIMENTO" ON "PROYECTO"."ALIMENTOS" ("ID_ALIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TERNERA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_TERNERA" ON "PROYECTO"."TERNERAS" ("ID_TERNERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ALIMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_ALIMENTO" ON "PROYECTO"."ALIMENTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_MADRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_MADRE" ON "PROYECTO"."MADRES" ("NRO_CARAVANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MADRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_MADRE" ON "PROYECTO"."MADRES" ("ID_MADRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONSUMO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_CONSUMO" ON "PROYECTO"."CONSUMOS" ("ID_ALIMENTO", "ID_TERNERA", "FECHA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_MEDICAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_MEDICAMENTO" ON "PROYECTO"."MEDICAMENTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_PADRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_PADRE" ON "PROYECTO"."PADRES" ("NRO_CARAVANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PESO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_PESO" ON "PROYECTO"."PESOS" ("ID_PESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONSUMO1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_CONSUMO1" ON "PROYECTO"."CONSUMOS" ("ID_CONSUMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIENE_ENFERMEDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_TIENE_ENFERMEDAD" ON "PROYECTO"."TIENE_ENFERMEDADES" ("ID_ENFERMEDAD", "ID_TERNERA", "FEC_DESDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ENFERMEDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_ENFERMEDAD" ON "PROYECTO"."ENFERMEDADES" ("ID_ENFERMEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_UNIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_UNIDAD" ON "PROYECTO"."UNIDADES" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."USUARIOS" ADD CONSTRAINT "CHK_USU_PERFIL" CHECK (
PERFIL IN('PERSONAL','ENCARGADO')) ENABLE;
 
  ALTER TABLE "PROYECTO"."USUARIOS" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("PERFIL" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."USUARIOS" ADD CONSTRAINT "UK_USUARIO" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MADRES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."MADRES" ADD CONSTRAINT "PK_MADRE" PRIMARY KEY ("ID_MADRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."MADRES" MODIFY ("ID_MADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."MADRES" MODIFY ("NRO_CARAVANA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."MADRES" ADD CONSTRAINT "UK_MADRE" UNIQUE ("NRO_CARAVANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TERNERAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."TERNERAS" ADD CONSTRAINT "CHK_TER_RAZA" CHECK (
RAZA IN('HOLANDO','JERSEY','CRUZA')) ENABLE;
 
  ALTER TABLE "PROYECTO"."TERNERAS" ADD CONSTRAINT "PK_TERNERA" PRIMARY KEY ("ID_TERNERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("ID_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("NRO_CARAVANA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("ID_GUACHERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("ID_PADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("ID_MADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("FEC_NACIMIENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("PESO_NACIMIENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("RAZA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" MODIFY ("PARTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TERNERAS" ADD CONSTRAINT "UK_TERNERA" UNIQUE ("NRO_CARAVANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIDADES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."UNIDADES" ADD CONSTRAINT "PK_UNIDAD" PRIMARY KEY ("ID_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."UNIDADES" MODIFY ("ID_UNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."UNIDADES" MODIFY ("UNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."UNIDADES" ADD CONSTRAINT "UK_UNIDAD" UNIQUE ("UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PADRES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."PADRES" ADD CONSTRAINT "PK_PADRE" PRIMARY KEY ("ID_PADRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."PADRES" MODIFY ("ID_PADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."PADRES" MODIFY ("NRO_CARAVANA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."PADRES" ADD CONSTRAINT "UK_PADRE" UNIQUE ("NRO_CARAVANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PESOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."PESOS" ADD CONSTRAINT "CHK_PESO_TIPO" CHECK (
TIPO_REGISTRO IN('SEMANAL','QUINCENAL')) ENABLE;
 
  ALTER TABLE "PROYECTO"."PESOS" ADD CONSTRAINT "PK_PESO" PRIMARY KEY ("ID_PESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."PESOS" MODIFY ("ID_PESO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."PESOS" MODIFY ("TIPO_REGISTRO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."PESOS" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."PESOS" MODIFY ("PESO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."PESOS" MODIFY ("ID_TERNERA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSUMOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."CONSUMOS" ADD CONSTRAINT "PK_CONSUMO" PRIMARY KEY ("ID_CONSUMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."CONSUMOS" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."CONSUMOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."CONSUMOS" MODIFY ("ID_ALIMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."CONSUMOS" MODIFY ("ID_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."CONSUMOS" MODIFY ("ID_CONSUMO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENFERMEDADES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ENFERMEDADES" ADD CONSTRAINT "CHK_ENF_GRADO" CHECK (
GRADO_GRAVEDAD IN(1,2,3)) ENABLE;
 
  ALTER TABLE "PROYECTO"."ENFERMEDADES" ADD CONSTRAINT "PK_ENFERMEDAD" PRIMARY KEY ("ID_ENFERMEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."ENFERMEDADES" MODIFY ("ID_ENFERMEDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ENFERMEDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ENFERMEDADES" MODIFY ("GRADO_GRAVEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIENE_ENFERMEDADES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" ADD CONSTRAINT "PK_TIENE_ENFERMEDAD" PRIMARY KEY ("ID_TIENE_ENF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" MODIFY ("FEC_DESDE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" MODIFY ("ID_ENFERMEDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" MODIFY ("ID_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" MODIFY ("ID_TIENE_ENF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GUACHERAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."GUACHERAS" ADD CONSTRAINT "PK_GUACHERA" PRIMARY KEY ("ID_GUACHERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."GUACHERAS" MODIFY ("ID_GUACHERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."GUACHERAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALIMENTOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ALIMENTOS" ADD CONSTRAINT "PK_ALIMENTO" PRIMARY KEY ("ID_ALIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."ALIMENTOS" MODIFY ("ID_ALIMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ALIMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ALIMENTOS" MODIFY ("COSTO_UNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ALIMENTOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ALIMENTOS" MODIFY ("ID_UNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."ALIMENTOS" ADD CONSTRAINT "UK_ALIMENTO" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDICAMENTOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."MEDICAMENTOS" ADD CONSTRAINT "PK_MEDICAMENTO" PRIMARY KEY ("ID_MEDICAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."MEDICAMENTOS" MODIFY ("ID_MEDICAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."MEDICAMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."MEDICAMENTOS" MODIFY ("DOSIS" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."MEDICAMENTOS" MODIFY ("COSTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."MEDICAMENTOS" ADD CONSTRAINT "UK_MEDICAMENTO" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOSIS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DOSIS" ADD CONSTRAINT "PK_DOSIS" PRIMARY KEY ("ID_DOSIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROYECTO"."DOSIS" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."DOSIS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."DOSIS" MODIFY ("ID_MEDICAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."DOSIS" MODIFY ("ID_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROYECTO"."DOSIS" MODIFY ("ID_DOSIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALIMENTOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ALIMENTOS" ADD CONSTRAINT "FK_ALIMENTO_UNIDAD" FOREIGN KEY ("ID_UNIDAD")
	  REFERENCES "PROYECTO"."UNIDADES" ("ID_UNIDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSUMOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."CONSUMOS" ADD CONSTRAINT "FK_CONSUMO_ALIMENTO" FOREIGN KEY ("ID_ALIMENTO")
	  REFERENCES "PROYECTO"."ALIMENTOS" ("ID_ALIMENTO") ENABLE;
 
  ALTER TABLE "PROYECTO"."CONSUMOS" ADD CONSTRAINT "FK_CONSUMO_TERNERA" FOREIGN KEY ("ID_TERNERA")
	  REFERENCES "PROYECTO"."TERNERAS" ("ID_TERNERA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOSIS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DOSIS" ADD CONSTRAINT "FK_DOSIS_MEDICAMENTO" FOREIGN KEY ("ID_MEDICAMENTO")
	  REFERENCES "PROYECTO"."MEDICAMENTOS" ("ID_MEDICAMENTO") ENABLE;
 
  ALTER TABLE "PROYECTO"."DOSIS" ADD CONSTRAINT "FK_DOSIS_TERNERA" FOREIGN KEY ("ID_TERNERA")
	  REFERENCES "PROYECTO"."TERNERAS" ("ID_TERNERA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GUACHERAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."GUACHERAS" ADD CONSTRAINT "GUACHERAS_FK1" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PROYECTO"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PESOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."PESOS" ADD CONSTRAINT "FK_PESO_TERNERA" FOREIGN KEY ("ID_TERNERA")
	  REFERENCES "PROYECTO"."TERNERAS" ("ID_TERNERA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TERNERAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."TERNERAS" ADD CONSTRAINT "FK_TERNERA_GUACHERA" FOREIGN KEY ("ID_GUACHERA")
	  REFERENCES "PROYECTO"."GUACHERAS" ("ID_GUACHERA") ENABLE;
 
  ALTER TABLE "PROYECTO"."TERNERAS" ADD CONSTRAINT "FK_TERNERA_MADRE" FOREIGN KEY ("ID_MADRE")
	  REFERENCES "PROYECTO"."MADRES" ("ID_MADRE") ENABLE;
 
  ALTER TABLE "PROYECTO"."TERNERAS" ADD CONSTRAINT "FK_TERNERA_PADRE" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "PROYECTO"."PADRES" ("ID_PADRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIENE_ENFERMEDADES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" ADD CONSTRAINT "FK_TIENE_ENF_MEDICAMENTO" FOREIGN KEY ("ID_ENFERMEDAD")
	  REFERENCES "PROYECTO"."ENFERMEDADES" ("ID_ENFERMEDAD") ENABLE;
 
  ALTER TABLE "PROYECTO"."TIENE_ENFERMEDADES" ADD CONSTRAINT "FK_TIENE_ENF_TERNERA" FOREIGN KEY ("ID_TERNERA")
	  REFERENCES "PROYECTO"."TERNERAS" ("ID_TERNERA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ALIMENTO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_ALIMENTO_SEQ" 
BEFORE INSERT 
ON ALIMENTOS
FOR EACH ROW
BEGIN
SELECT SEQ_ID_ALIMENTO.NEXTVAL
INTO :NEW.ID_ALIMENTO
FROM DUAL;
END T_ALIMENTO_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_ALIMENTO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CONSUMO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_CONSUMO_SEQ" 
BEFORE INSERT 
ON CONSUMOS
FOR EACH ROW
BEGIN
SELECT SEQ_ID_CONSUMO.NEXTVAL
INTO :NEW.ID_CONSUMO
FROM DUAL;
END T_CONSUMO_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_CONSUMO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_DOSIS_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_DOSIS_SEQ" 
BEFORE INSERT 
ON DOSIS 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_DOSIS.NEXTVAL
INTO :NEW.ID_DOSIS
FROM DUAL;
END T_DOSIS_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_DOSIS_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ENFERMEDAD_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_ENFERMEDAD_SEQ" 
BEFORE INSERT 
ON ENfERMEDADES 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_ENFERMEDAD.NEXTVAL
INTO :NEW.ID_ENFERMEDAD
FROM DUAL;
END T_ENFERMEDAD_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_ENFERMEDAD_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_MADRE_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_MADRE_SEQ" 
BEFORE INSERT 
ON MADRES 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_MADRE.NEXTVAL
INTO :NEW.ID_MADRE
FROM DUAL;
END T_MADRE_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_MADRE_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_MEDICAMENTO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_MEDICAMENTO_SEQ" 
BEFORE INSERT 
ON MEDICAMENTOS 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_MEDICAMENTO.NEXTVAL
INTO :NEW.ID_MEDICAMENTO
FROM DUAL;
END T_MEDICAMENTO_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_MEDICAMENTO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_PADRE_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_PADRE_SEQ" 
BEFORE INSERT 
ON PADRES 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_PADRE.NEXTVAL
INTO :NEW.ID_PADRE
FROM DUAL;
END T_PADRE_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_PADRE_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_PESO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_PESO_SEQ" 
BEFORE INSERT 
ON PESOS 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_PESO.NEXTVAL
INTO :NEW.ID_PESO
FROM DUAL;
END T_PESO_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_PESO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_TERNERA_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_TERNERA_SEQ" 
BEFORE INSERT 
ON TERNERAS 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_TERNERA.NEXTVAL
INTO :NEW.ID_TERNERA
FROM DUAL;
END T_TERNERA_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_TERNERA_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_TIENE_ENF_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_TIENE_ENF_SEQ" 
BEFORE INSERT 
ON TIENE_ENFERMEDADES
FOR EACH ROW
BEGIN
SELECT SEQ_ID_TIENE_ENF.NEXTVAL
INTO :NEW.ID_TIENE_ENF
FROM DUAL;
END T_TIENE_ENF_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_TIENE_ENF_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_USUARIO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROYECTO"."T_USUARIO_SEQ" 
BEFORE INSERT 
ON USUARIOS 
FOR EACH ROW
BEGIN
SELECT SEQ_ID_USUARIO.NEXTVAL
INTO :NEW.ID_USUARIO
FROM DUAL;
END T_USUARIO_SEQ;
/
ALTER TRIGGER "PROYECTO"."T_USUARIO_SEQ" ENABLE;
